language: ruby
script: bundle exec rake test
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - ruby-head
  - jruby-9
  - rbx-2
addons:
  code_climate:
    repo_token: 6f4b7c1f44b29f414ffb9b243b1f83cf5fa40eb297b4cd0c7761bf960487a8eb
matrix:
  allow_failures:
    - rvm: ruby-head